#ifndef rand_h
#define rand_h

#include <stdlib.h>
#include <stdint.h>

/**
 * Print point for each generated byte
 */
#define RAND_FLAG_PROGRESS 0x1

/**
 * Get len secure bytes from OS
 */
int secure_random_bytes(uint8_t *b, size_t len, int flags);

#endif